spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5435/devsu_db
spring.datasource.username=devsu_user
spring.datasource.password=devsu_password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server port customization
server.port=${SERVER_PORT:8085}

# Error details
server.error.include-message=always
spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false
